# Generated by Django 5.2.15 on 2026-07-13 14:02

import django.db.models.deletion
import django.utils.timezone
import monitor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Πώς θα φαίνεται η συσκευή στο dashboard. π.χ. "Αποθήκη Α" ή "Εργοτάξιο Βόρεια πύλη".', max_length=100)),
                ('location', models.CharField(blank=True, help_text='Προαιρετικό: πού βρίσκεται φυσικά η συσκευή (εμφανίζεται δίπλα στο όνομα).', max_length=150)),
                ('api_key', models.CharField(default=monitor.models.generate_api_key, editable=False, max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Ξετίκαρε για να σταματήσεις προσωρινά να εμφανίζεται/δέχεται δεδομένα, χωρίς να τη διαγράψεις.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ecowitt_passkey', models.CharField(blank=True, help_text='ΜΟΝΟ για Ecowitt Gateway: το PASSKEY της συσκευής (το βρίσκεις στην εφαρμογή WS View Plus, στα στοιχεία του Gateway). Ταυτοποιεί από ποιο Gateway ήρθε η μέτρηση.', max_length=64)),
                ('ecowitt_channel', models.PositiveSmallIntegerField(blank=True, help_text='ΜΟΝΟ για πολυκάναλο αισθητήρα WH31 (1-8): ποιο κανάλι αντιστοιχεί σε αυτή τη συσκευή. Άφησέ το κενό για τον κύριο/μοναδικό αισθητήρα (WN32/WH32).', null=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('last_temperature', models.FloatField(blank=True, null=True)),
                ('last_humidity', models.FloatField(blank=True, null=True)),
                ('last_signal_level', models.CharField(blank=True, max_length=100)),
                ('last_severity', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HeatIndexRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.IntegerField(help_text='Θερμοκρασία σε ακέραιους βαθμούς Κελσίου (°C).', unique=True)),
                ('max_humidity_level1', models.FloatField(help_text='Μέγιστη υγρασία (%) για Επίπεδο 1 (συνεχής εργασία).')),
                ('max_humidity_level2', models.FloatField(help_text='Μέγιστη υγρασία (%) για Επίπεδο 2.')),
                ('max_humidity_level3', models.FloatField(help_text='Μέγιστη υγρασία (%) για Επίπεδο 3.')),
                ('max_humidity_level4', models.FloatField(help_text='Μέγιστη υγρασία (%) για Επίπεδο 4. Πάνω από αυτό = Επίπεδο 5.')),
            ],
            options={
                'ordering': ['temperature'],
            },
        ),
        migrations.CreateModel(
            name='RiskLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_number', models.PositiveSmallIntegerField(unique=True)),
                ('work_break_schedule', models.CharField(blank=True, help_text='Πρόγραμμα διαλείμματος σε απλά λόγια, π.χ. "15 λεπτά διάλειμμα ανά ώρα".', max_length=100)),
                ('message', models.CharField(blank=True, help_text='Το κείμενο του SMS που θα σταλεί όταν μια συσκευή φτάσει σε αυτό το επίπεδο.', max_length=255)),
                ('notify', models.BooleanField(default=True, help_text='Τικ = στείλε SMS σε αυτό το επίπεδο. Ξετίκαρε για σιωπηλή καταγραφή μόνο.')),
            ],
            options={
                'ordering': ['level_number'],
            },
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Όνομα για αναγνώριση, π.χ. "Γιώργος - Επόπτης".', max_length=100)),
                ('phone_number', models.CharField(blank=True, help_text='Αριθμός κινητού σε διεθνή μορφή (E.164), π.χ. +35799123456. Εδώ θα σταλεί το SMS.', max_length=32)),
                ('receive_sms', models.BooleanField(default=True, help_text='Τικ = να λαμβάνει SMS ειδοποιήσεις.')),
                ('is_active', models.BooleanField(default=True, help_text='Ξετίκαρε για προσωρινή παύση χωρίς διαγραφή.')),
                ('devices', models.ManyToManyField(blank=True, help_text='Για ποιες συσκευές θα ειδοποιείται. Χωρίς καμία επιλογή = καμία ειδοποίηση.', related_name='recipients', to='monitor.device')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_level', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=255)),
                ('channel', models.CharField(default='sms', max_length=20)),
                ('success', models.BooleanField(default=False)),
                ('error', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='monitor.device')),
                ('recipient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitor.recipient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(help_text='Degrees Celsius')),
                ('humidity', models.FloatField(help_text='Relative humidity %')),
                ('signal_level', models.CharField(blank=True, max_length=100)),
                ('severity', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='monitor.device')),
                ('matched_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitor.risklevel')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['device', 'created_at'], name='monitor_rea_device__781a65_idx')],
            },
        ),
    ]
