# Generated by Django 5.2.15 on 2026-07-23 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='agromet_station_code',
            field=models.CharField(blank=True, editable=False, max_length=32),
        ),
        migrations.AddField(
            model_name='device',
            name='worksite_address',
            field=models.CharField(blank=True, help_text='Η διεύθυνση του εργοταξίου (π.χ. "Λεωφόρος Μακαρίου 25, Λευκωσία"). Οι συντεταγμένες και ο πλησιέστερος σταθμός υπολογίζονται αυτόματα.', max_length=255),
        ),
        migrations.AddField(
            model_name='device',
            name='worksite_latitude',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='worksite_longitude',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
    ]
