# Generated by Django 5.2.15 on 2026-07-23 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_device_agromet_station_code_device_worksite_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='agromet_station_code',
            field=models.CharField(blank=True, default='', editable=False, max_length=32),
        ),
    ]
