# Generated by Django 5.2.15 on 2026-07-02 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_flexible_severity_levels'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='reading',
            new_name='monitor_rea_device__781a65_idx',
            old_name='monitor_rea_device__1e1d0a_idx',
        ),
    ]
