# Generated by Django 5.2.15 on 2026-07-23 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_alter_device_agromet_station_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agromet_poll_minutes', models.PositiveIntegerField(default=10, help_text='Κάθε πόσα λεπτά να ελέγχεται το AgroMet.')),
            ],
        ),
    ]
