# Generated by Django 5.2.15 on 2026-07-23 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0005_stationobservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='data_source',
            field=models.CharField(choices=[('sensor', 'Φυσικός αισθητήρας (API key / Ecowitt)'), ('agromet', 'AgroMet (διεύθυνση εργοταξίου)')], default='sensor', help_text='Διάλεξε  τρόπο λήψης δεδομένων ανά συσκευή ', max_length=10),
        ),
    ]
