# Generated by Django 5.2.15 on 2026-07-05 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0006_ecowitt_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='reading',
            new_name='monitor_rea_device__781a65_idx',
            old_name='monitor_rea_device__1e1d0a_idx',
        ),
        migrations.AlterField(
            model_name='device',
            name='ecowitt_channel',
            field=models.PositiveSmallIntegerField(blank=True, help_text='ΜΟΝΟ για πολυκάναλο αισθητήρα WH31 (1-8): ποιο κανάλι αντιστοιχεί σε αυτή τη συσκευή. Άφησέ το κενό για τον κύριο/μοναδικό αισθητήρα (WN32/WH32).', null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='ecowitt_passkey',
            field=models.CharField(blank=True, help_text='ΜΟΝΟ για Ecowitt Gateway: το PASSKEY της συσκευής (το βρίσκεις στην εφαρμογή WS View Plus, στα στοιχεία του Gateway). Ταυτοποιεί από ποιο Gateway ήρθε η μέτρηση.', max_length=64),
        ),
        migrations.AlterField(
            model_name='device',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Ξετίκαρε για να σταματήσεις προσωρινά να εμφανίζεται/δέχεται δεδομένα, χωρίς να τη διαγράψεις.'),
        ),
        migrations.AlterField(
            model_name='device',
            name='location',
            field=models.CharField(blank=True, help_text='Προαιρετικό: πού βρίσκεται φυσικά η συσκευή (εμφανίζεται δίπλα στο όνομα).', max_length=150),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(help_text='Πώς θα φαίνεται η συσκευή στο dashboard. π.χ. "Αποθήκη Α" ή "Εργοτάξιο Βόρεια πύλη".', max_length=100),
        ),
        migrations.AlterField(
            model_name='heatindexrow',
            name='max_humidity_level1',
            field=models.FloatField(help_text='Μέγιστη υγρασία (%) για Επίπεδο 1 (συνεχής εργασία).'),
        ),
        migrations.AlterField(
            model_name='heatindexrow',
            name='max_humidity_level2',
            field=models.FloatField(help_text='Μέγιστη υγρασία (%) για Επίπεδο 2.'),
        ),
        migrations.AlterField(
            model_name='heatindexrow',
            name='max_humidity_level3',
            field=models.FloatField(help_text='Μέγιστη υγρασία (%) για Επίπεδο 3.'),
        ),
        migrations.AlterField(
            model_name='heatindexrow',
            name='max_humidity_level4',
            field=models.FloatField(help_text='Μέγιστη υγρασία (%) για Επίπεδο 4. Πάνω από αυτό = Επίπεδο 5.'),
        ),
        migrations.AlterField(
            model_name='heatindexrow',
            name='temperature',
            field=models.IntegerField(help_text='Θερμοκρασία σε ακέραιους βαθμούς Κελσίου (°C).', unique=True),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='devices',
            field=models.ManyToManyField(blank=True, help_text='Για ποιες συσκευές θα ειδοποιείται. Χωρίς καμία επιλογή = καμία ειδοποίηση.', related_name='recipients', to='monitor.device'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Ξετίκαρε για προσωρινή παύση χωρίς διαγραφή.'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='name',
            field=models.CharField(help_text='Όνομα για αναγνώριση, π.χ. "Γιώργος - Επόπτης".', max_length=100),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Αριθμός κινητού σε διεθνή μορφή (E.164), π.χ. +35799123456. Εδώ θα σταλεί το SMS.', max_length=32),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='receive_sms',
            field=models.BooleanField(default=True, help_text='Τικ = να λαμβάνει SMS ειδοποιήσεις.'),
        ),
        migrations.AlterField(
            model_name='risklevel',
            name='message',
            field=models.CharField(blank=True, help_text='Το κείμενο του SMS που θα σταλεί όταν μια συσκευή φτάσει σε αυτό το επίπεδο.', max_length=255),
        ),
        migrations.AlterField(
            model_name='risklevel',
            name='notify',
            field=models.BooleanField(default=True, help_text='Τικ = στείλε SMS σε αυτό το επίπεδο. Ξετίκαρε για σιωπηλή καταγραφή μόνο.'),
        ),
        migrations.AlterField(
            model_name='risklevel',
            name='work_break_schedule',
            field=models.CharField(blank=True, help_text='Πρόγραμμα διαλείμματος σε απλά λόγια, π.χ. "15 λεπτά διάλειμμα ανά ώρα".', max_length=100),
        ),
    ]
